sudo: true
language: haskell

git:
  depth: 2

cabal: "2.4"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
  - ghc: 8.6.4

install:
  - |
    ghc --version
    cabal --version
    cabal new-update
    cabal new-build --enable-tests --enable-benchmarks

script:
  - cabal new-test --enable-tests
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

notifications:
  email: false
